### ISSUE TITLE
开个新坑，自己用Rust撸一个简单的区块链

### ISSUE THREAD

**Issue by AlexiaChen** [AlexiaChen/AlexiaChen.github.io#136]
先仿照BTC的初版这样弄吧。共识暂时不考虑模块化，直接PoW。P2P也是Inv广播的机制，Tx遵循UTXO模型。慢慢写，反正是业余项目。主要以尝试用Rust构建稍微大一点的项目为目的。

大概会用到tokio actix 和一些基本的第三方基础设施。p2p方面可能暂时不会用libp2p而是动手仿照BTC的初版写。这也是我取名为simple chain的原因。毕竟也是自己开始动手写一个链。

深刻知道，能看懂部分顶尖大型项目的模块的源码是一回事，自己写又是另一回事，长期管中窥豹也不可取吧。

github地址： https://github.com/AlexiaChen/simple-chain

**Comment by songtianyi** [comment]
NPoS 现在用的比较多吧

**Comment by AlexiaChen** [comment]
> NPoS 现在用的比较多吧

主体是PoS，也有BFT家族的公链。

**Comment by songtianyi** [comment]
感觉坑有点大

**Comment by AlexiaChen** [comment]
> 感觉坑有点大

对于业余项目确实坑有点大，哈哈
