### ISSUE TITLE
在央企中一个很有意思的地方

### ISSUE THREAD

**Issue by AlexiaChen** [AlexiaChen/AlexiaChen.github.io#151]
因为央企随着国企改革里面早就去行政化了，所以里面所谓的编制也已经不是体制内的编制概念了，是跟央企直签合同的正式工，但是大部分还保留有编制这样的说法，因为里面的风气跟体制内几乎一模一样，岗级也跟公务员级别可以大致对应上。

当然话说回来，要说有编制也没错，因为央企的工资总额是固定的，现在国企又实行三重一大，人员一旦经过层层选拔（开总办会- 网申- 资格审查 - 笔试 - 结构化面试 - 政审 - 党委会审查资料）最终录用，人力信息就要上报央企的上级单位，录入整个集团的系统。“编制”员工（正式合同工）这样就是在岗在册了。

经过上面的程序，你就可以看出来，央企领导开除一个人是很难的，一般是吃力不讨好的，人事权是在上级单位的，你要开人，还得上报审批，上级单位会觉得当初名额这边是你上报的现在又要开除，你是什么意思？ 这人犯法，有重大违纪吗？下次减少你人力名额数量，所以麻烦得很，比方说，一般央企校园和社会招聘都是由各省的省公司（省直单位）组织，各地市分别面试，上报结果材料等等。除了开人难还有就是央企国企每年都要承担社会责任（这是政治任务），消化每年大部分的高校毕业生，尽可能保证大部分家庭稳定，不能随便失业。所以稳定性上还是高过大部分民营企业和外企的，但是这样一来的话，工资的上限会很低，撑不饱，饿不死，你一眼就可以望到头。

还有就是，对于某个央企来说，它本身是个庞大的机构，这里我们只讨论它的全资子公司，或者它的分公司。所以一般来说央企的组织架构就有了树状的层级结构，分为集团总部，省公司，地市公司，区县公司。跟体制内的检察院，法院，医保局，教育局 公安局等，比如公安有大概类似的层级，公安也分为公安部，省公安厅（省厅），市公安局（市局）。从这点来看，虽然央企去行政化了，但是组织概念还有些体制残留，毕竟央企一般是把控国家经济命脉的公司，跟一般国企不太一样。所以你看到了，央企集团总部一般是部委级，省公司属于省厅级别，依次类推。集团总部的央企员工因为靠近中央，跟他们打交道的大部分都是部委级的公务员，永远处于改革的漩涡中心，省公司属于厅级，一般省公司的一把手一般也是正厅，央企的高层一般都是公务员平级调动（我们单位的一把手之前就是某地市的市委书记调任），一般内部提拔可能性不大，他们高层是货真价实的行政编制，已经跳出央企内部级别的五行外了。

说了这么多，还是讲讲这央企隐约的“行政”级别吧，一般集团总部的科室主任（处级）从级别上来讲对应省公司的部门一把手（处级），集团部门一把手（厅级）对应省公司一把手（厅级），省公司的部门一把手对应市公司的一把手，省公司的科室主任（科级）对应市公司部门一把手（科级）。当然，二把手也是这样，省公司的部门内部分管领导（副总），对应市公司的副总经理，虽然级别按理来说一样，但是往往下一级单位跟你平级的实权更大，因为管了更多的员工。所以当你平级被调动到下一集单位，一般来说就是相当于升职了，历练几年再回来上级部门。

所以当你听到在央企里面叫什么处长，千万别惊讶，这是以前的体制风气残留，特别是老央企员工，虽然改革了，但他们还是很在意很自豪的事情，你这么一叫，他们还挺高兴的，我还听到过有位央企老员工打趣说，乙方请吃饭我是肯定不能去的，不然我就被开除公职了，我当时奇怪了，只有公务员才被叫做公职，怎么他们也这么说，原来是这样，可能当年来说，他们觉得自己算“公务员”吧，多这样叫，这样可以给老员工脸上贴金，也蛮好的。

**Comment by AlexiaChen** [comment]
> 对，以及这些领导，公司里面高层领导叫院长什么的没毛病，一般处长或者部长，或者总工，叫他们“老师”也是可以的，也爱听。
> 尤其有的领导本身就是大学老师出来的，叫老师更没毛病了。
> 国企现在不一定工资稳定了，看具体情况，有可能会某些情况会很高，然后看企业的操作可能工资下限变得很低。
> 以及国企，尤其很多具有参公性质的，确实会有点像公职，但是和公务员还是会有很大区别，和事业单位会很像，有的本身就是事业单位改的国企，和上级单位，或者省属部门关系密切。所以实际是会有点像公务员，包括一些福利政策啥的，会接近。
> 说公职的话，好像国企里面确实是可以对应一些行政级别，小的国企或者级别低的不管，省属国企啥的，好像是会有行政级别。央企就应该更会有行政级别了。具体是有事业单位编制还是啥的，就不知道了，也可能有的领导本身就有公务员编制。
> 
> 你现在跑央企去了？我是从国企跳出来跑了，工资降的厉害。

@kentzhang-geek 大佬离开昆明啦？省设计院降薪厉害？是的，我进了央企，中国电信省公司，待遇比预期的低，又想走了。之前我那个公司不是倒闭了嘛，想必你也知道了，后来找了个远程的公司，办公了半年，工资是发USDT，也不是很稳定，就来央企了，结果是一个大坑啊！你在广州了？

**Comment by kentzhang-geek** [comment]
> > 对，以及这些领导，公司里面高层领导叫院长什么的没毛病，一般处长或者部长，或者总工，叫他们“老师”也是可以的，也爱听。
> > 尤其有的领导本身就是大学老师出来的，叫老师更没毛病了。
> > 国企现在不一定工资稳定了，看具体情况，有可能会某些情况会很高，然后看企业的操作可能工资下限变得很低。
> > 以及国企，尤其很多具有参公性质的，确实会有点像公职，但是和公务员还是会有很大区别，和事业单位会很像，有的本身就是事业单位改的国企，和上级单位，或者省属部门关系密切。所以实际是会有点像公务员，包括一些福利政策啥的，会接近。
> > 说公职的话，好像国企里面确实是可以对应一些行政级别，小的国企或者级别低的不管，省属国企啥的，好像是会有行政级别。央企就应该更会有行政级别了。具体是有事业单位编制还是啥的，就不知道了，也可能有的领导本身就有公务员编制。
> > 你现在跑央企去了？我是从国企跳出来跑了，工资降的厉害。
> 
> @kentzhang-geek 大佬离开昆明啦？省设计院降薪厉害？是的，我进了央企，中国电信省公司，待遇比预期的低，又想走了。之前我那个公司不是倒闭了嘛，想必你也知道了，后来找了个远程的公司，办公了半年，工资是发USDT，也不是很稳定，就来央企了，结果是一个大坑啊！你在广州了？

@AlexiaChen 大佬雷猴啊，我在广州了，省交院之前那个部门确实降薪厉害，估计打七折吧。我还想央企会不会好点，结果也坑？我是有个同事在我之前跑广州猪厂了，后来我就找他内推来了猪厂，然后现在他跑鹅厂去了┓( ´∀` )┏

**Comment by kentzhang-geek** [comment]
可能还不止七折，最坏可能应该是税前打四折或者五折，这种情况我就断供或者断顿了，所以没敢留。

**Comment by AlexiaChen** [comment]
> > > 对，以及这些领导，公司里面高层领导叫院长什么的没毛病，一般处长或者部长，或者总工，叫他们“老师”也是可以的，也爱听。
> > > 尤其有的领导本身就是大学老师出来的，叫老师更没毛病了。
> > > 国企现在不一定工资稳定了，看具体情况，有可能会某些情况会很高，然后看企业的操作可能工资下限变得很低。
> > > 以及国企，尤其很多具有参公性质的，确实会有点像公职，但是和公务员还是会有很大区别，和事业单位会很像，有的本身就是事业单位改的国企，和上级单位，或者省属部门关系密切。所以实际是会有点像公务员，包括一些福利政策啥的，会接近。
> > > 说公职的话，好像国企里面确实是可以对应一些行政级别，小的国企或者级别低的不管，省属国企啥的，好像是会有行政级别。央企就应该更会有行政级别了。具体是有事业单位编制还是啥的，就不知道了，也可能有的领导本身就有公务员编制。
> > > 你现在跑央企去了？我是从国企跳出来跑了，工资降的厉害。
> > 
> > @kentzhang-geek 大佬离开昆明啦？省设计院降薪厉害？是的，我进了央企，中国电信省公司，待遇比预期的低，又想走了。之前我那个公司不是倒闭了嘛，想必你也知道了，后来找了个远程的公司，办公了半年，工资是发USDT，也不是很稳定，就来央企了，结果是一个大坑啊！你在广州了？
> 
> @AlexiaChen 大佬雷猴啊，我在广州了，省交院之前那个部门确实降薪厉害，估计打七折吧。我还想央企会不会好点，结果也坑？我是有个同事在我之前跑广州猪厂了，后来我就找他内推来了猪厂，然后现在他跑鹅厂去了┓( ´∀` )┏

@kentzhang-geek  雷猴是啥，哈哈。是省交研院吗？我记得那里工资很高，我现在在中国电信省公司到手就5k，年终奖3w，太坑了。去猪场又是你一个同事，不会是姚益吧？来电信面试的姚益就是最后没来，拖家带口去了网易。电信一言难尽。

**Comment by AlexiaChen** [comment]
> 可能还不止七折，最坏可能应该是税前打四折或者五折，这种情况我就断供或者断顿了，所以没敢留。

到底降了多少，直接断供，我倒是可以还月供，就是这个收入和工作量性价比低，没法摸鱼，摸鱼的时候我一般会搞些自己的兴趣，现在根本没时间。电信，移动本质上就是一个运营商销售公司。我们的项目都有乙方做，我们做的事项目经理的角色。

**Comment by kentzhang-geek** [comment]
@AlexiaChen 雷猴就是广东话的你好┓( ´∀` )┏，可能就是你说的省交研院，省交通规划设计研究院，交投下面那个，老早以前不是交投的是属于省交通厅的事业单位，大概十年前改国企了么。工资确实高，正常情况大概是纯程序员在云南省能拿到的最高水平。但是情况不正常么，打折打的厉害，目前见过的下限到手1w多点，外加公积金4k多，那里每月工资不等，一般年初低年底高，1w就是年初最低的时候，所以一般我都按年看，假如一直留着大概那年应该相当于巅峰期五折多吧。如果工资一直是巅峰期水准么，我估计我都可能不会跑，巅峰水平┓( ´∀` )┏离职了都还是低调点得了，反正巅峰也就那一年。
不是姚益，是蒋斯，你可能不认识，我来猪厂没多久他就跳去鹅厂了。
我月供就9k，媳妇不上班在家里，所以工资降到1w的时候生活费就已经从存款里面走一些了，离职的时候都得贷款搬家，挺愁。
跳槽到网易么，和巅峰期对比都接近double。再往上跳槽没意义了，涨不了多少，即便涨了多半涨的是股。

**Comment by AlexiaChen** [comment]
> @AlexiaChen 雷猴就是广东话的你好。可能就是你说的省交研院，省交通规划设计研究院，交投下面那个，老早以前不是交投的是属于省交通厅的事业单位，大概十年前改国企了么。工资确实高，正常情况大概是纯程序员在云南省能拿到的最高水平。但是情况不正常么，打折打的厉害，目前见过的下限到手1w多点，外加公积金4k多，那里每月工资不等，一般年初低年底高，1w就是年初最低的时候，所以一般我都按年看，假如一直留着大概那年应该相当于巅峰期五折多吧。如果工资一直是巅峰期水准么，我估计我都可能不会跑，巅峰水平┓( ´∀` )┏离职了都还是低调点得了，反正巅峰也就那一年。
> 不是姚益，是蒋斯，你可能不认识，我来猪厂没多久他就跳去鹅厂了。
> 我月供就9k，媳妇不上班在家里，所以工资降到1w的时候生活费就已经从存款里面走一些了，离职的时候都得贷款搬家，挺愁。
> 跳槽到网易么，和巅峰期对比都接近double。再往上跳槽没意义了，涨不了多少，即便涨了多半涨的是股。

大佬厉害，我的巅峰期就是到手35k，给美国打工性价比高。6000美刀的样子。

**Comment by kentzhang-geek** [comment]
@AlexiaChen 大佬给美国打工赚美刀啊。不过你说的央企就是电信？

**Comment by AlexiaChen** [comment]
> @AlexiaChen 大佬给美国打工赚美刀啊。不过你说的央企就是电信？

是电信，就是我在的央企。我是云链 -> 硅谷一家区块链公司 ->  去年12月份来的中国电信省公司。

在电信做大数据平台的甲方，其实啥都学不到，都是乙方的厂商在做（浩鲸云，亚信，通服等），我是在企信部，更偏IT。云网部门偏网络和无线，他们的厂商一般是华为，爱立信，EMC之类的。昆明纯程序员其实大概也就在20k到25k税前了。

**Comment by kentzhang-geek** [comment]
@AlexiaChen 那时候降工资主要是政策影响，具体传言就不好说了，我们合同上只写5k，都是靠奖金，所以波动很大，年初年底差距大，丰年灾年差距也大。巅峰期就那一年到手近40吧。

**Comment by kentzhang-geek** [comment]
@AlexiaChen 电信到手5k就有点坑，年终3w也没啥意思，不过感觉昆明很多时候就只有这种质量的岗位，没啥好企业，要是猪厂在昆明就爽了。

**Comment by kentzhang-geek** [comment]
硅谷那个远程美元的咋不一直干？远程工作有坑？

**Comment by AlexiaChen** [comment]
> 硅谷那个远程美元的咋不一直干？远程工作有坑？

求稳定，刚好家里有小孩了，自己把自己吓进去了，小孩还小精力不够，基本没时间看书，看数学，写点业余代码。远程我经常被家里的琐事打断，慢慢也会脱离社会，所以也是综合因素了。其实现在回头来看，只要想明白就好，没什么可怕的了。只是我出不去云南了，再找也是找远程。

**Comment by AlexiaChen** [comment]
> @AlexiaChen 电信到手5k就有点坑，年终3w也没啥意思，不过感觉昆明很多时候就只有这种质量的岗位，没啥好企业，要是猪厂在昆明就爽了。

我不适合创业，就想做个打工的，工资不求多高。工作生活平衡，有时间搞业余研究。哈哈哈哈，在昆明这样的工作太难了。

**Comment by kentzhang-geek** [comment]
@AlexiaChen  有小孩确实，我和我媳妇都打算暂时不要小孩，先看看能不能出国，不能出国我觉得以我这种条件小孩也是从小受苦，我这种牛马模板又再来一遍。广州这边我工作还好，965，稳定，组里大佬众多能学东西，但是媳妇就不好找工作，并且广州这个生活环境以及房价，看了也是脑阔疼。大佬你远程的话就是得全英语吧，我现在就是在想办法搞英语。

昆明确实工作太难搞了，而且房价又起来了，我现在用广州的工资还昆明的月供，都觉得有点蛋疼，还加上广州的房租，蛋疼，很蛋疼。你要是想搞C++的话可以考虑关注下云交院，但是那个部门比较新，有风险，交科院可能也行。还有啥好单位我想想……可能北航昆明研究院也可以看看。

要是能忍工资跳水的话，云交院可能可以，即便部门撤了，人也一般裁不掉，有关系的话搞不好可以转到交投数据中心啥的。

感觉其实在昆明，就是靠家底和关系了，这两没有基本扯淡。有家底就能抗波动，有关系才好找工作和调动┓( ´∀` )┏

**Comment by kentzhang-geek** [comment]
> > @AlexiaChen 电信到手5k就有点坑，年终3w也没啥意思，不过感觉昆明很多时候就只有这种质量的岗位，没啥好企业，要是猪厂在昆明就爽了。
> 
> 我不适合创业，就想做个打工的，工资不求多高。工作生活平衡，有时间搞业余研究。哈哈哈哈，在昆明这样的工作太难了。

是啊，要是昆明工作能正常点，我也不想跑出来，跳了那么多次已经不指望了，尤其是我这种搞C++的。那个工作环境和商业环境就没法搞，之前我和我媳妇，大概就是我工资巅峰那阵子，在建工新城开店，综合体地面一楼沃尔玛旁边点，勉强收支平衡，实际就是不挣钱，大部分利润全给房租坑走了，房租高，客流低，消费低，完全没法搞，二楼的火锅店都开一家走一家的。
挺怀念开店的，确实开店有趣，就是昆明那个商业环境，开店都难赚钱。

**Comment by AlexiaChen** [comment]
> @AlexiaChen  有小孩确实，我和我媳妇都打算暂时不要小孩，先看看能不能出国，不能出国我觉得以我这种条件小孩也是从小受苦，我这种牛马模板又再来一遍。广州这边我工作还好，965，稳定，组里大佬众多能学东西，但是媳妇就不好找工作，并且广州这个生活环境以及房价，看了也是脑阔疼。大佬你远程的话就是得全英语吧，我现在就是在想办法搞英语。
> 
> 昆明确实工作太难搞了，而且房价又起来了，我现在用广州的工资还昆明的月供，都觉得有点蛋疼，还加上广州的房租，蛋疼，很蛋疼。你要是想搞C++的话可以考虑关注下云交院，但是那个部门比较新，有风险，交科院可能也行。还有啥好单位我想想……可能北航昆明研究院也可以看看。
> 
> 要是能忍工资跳水的话，云交院可能可以，即便部门撤了，人也一般裁不掉，有关系的话搞不好可以转到交投数据中心啥的。
> 
> 感觉其实在昆明，就是靠家底和关系了，这两没有基本扯淡。有家底就能抗波动，有关系才好找工作和调动┓( ´∀` )┏

话说，真不知道你月供咋这么高，买多大的房子，我认识昆明很多打工的程序员，比我俩小的，夫妻双方都是农村的没家底的（有些还会帮家里的弟弟），都买房了，月供4k多。你这个月供高的有点吓人。不要给自己太大压力嘛，多大能力买多大房啊。你这个真有点蛋疼了。我现在不太清楚昆明的私企是不是压榨，单休的多，所以不好搞。憋着难受。唉。

**Comment by kentzhang-geek** [comment]
@AlexiaChen 我当时想着国企，稳定，而且巅峰期工资那么高，先用公积金干掉一半，剩下4~5k就是毛毛雨，鬼知道买了房工资就打折么。房子不大但是确实好住，湖畔之梦，广福路端头上，小区里面有个湖，湖里有天鹅和大乌龟，那套房子还带个15m左右的阳台，一楼实际就是小花园。妈的在广州老想回去住，那个房子十分舒服。

**Comment by kentzhang-geek** [comment]
@AlexiaChen 昆明私企的话，除非是圈子里一些靠谱的人自己出来搞的公司，很多私企都很坑，一开始我在一家“创业”公司，合同都不签，口头股份忽悠起，项目失败工资就停；然后去了一家给高速路搞机电的，工资倒是稳定，就是一到周五喜欢叫你明天出差，没加班费，只给个一天100的出差费，出差就是深山老林乡村野店，啥精深东西也学不到，经常回昆明做两天Scala，刚缓过来，好嘛明天出差，艹。

**Comment by kentzhang-geek** [comment]
想想确实，昆明那个环境，云交院已经是天顶星了┓( ´∀` )┏
